leftnav:
- identifier: 8c875bf1-127e-35a4-fe81-7bb2105515b0
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 8e3bfae8-749a-c9e9-8e31-1bea76d7766b
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 81cf33e1-97d4-2bec-3690-e44300ef7307
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 1075859e-4cef-e748-703e-ab5bb16b1e24
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: 9d0aa708-904e-32ce-df48-fdaee682718c
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
